---
environment_variables:
  PORTAL_VERSION: "0.1.0-8"
git:
  branch: main
triggers:
  cron: "@daily"
clean_workspace: true
builders:
  - docker
docker_name: drive/portal
docker_tags:
  - "${PORTAL_VERSION}"
  - "latest"
docker_no_cache: true
