idps:
  - id: bth
    entityIDs:
      - http://fs.bth.se/adfs/services/trust
  - id: chalmers
    entityIDs:
      - http://idp.chalmers.se/adfs/services/trust
  - id: hhs
    entityIDs:
      - https://login.idp.hhs.se/idp/shibboleth
      - http://fds.idp.hhs.se/adfs/services/trust
  - id: du
    entityIDs:
      - https://login.du.se/idp/shibboleth
  - id: vinnova
    entityIDs:
      - http://sts.vinnova.se/adfs/services/trust
  - id: hh
    entityIDs:
      - https://idp.hh.se/idp/shibboleth
  - id: hj
    entityIDs:
      - http://adfs.ju.se/adfs/services/trust
  - id: kth
    entityIDs:
      - https://saml.sys.kth.se/idp/shibboleth
  - id: kau
    entityIDs:
      - https://weblogin.kau.se/idp/shibboleth
  - id: ki
    entityIDs:
      - https://login.ki.se/idp/shibboleth
  - id: konstfack
    entityIDs:
      - https://idp-v2.konstfack.se/adfs/services/trust
      - https://connect.eduid.se/konstfack
  - id: hkr
    entityIDs:
      - https://idp.hkr.se/idp/shibboleth
  - id: liu
    entityIDs:
      - http://fs.liu.se/adfs/services/trust
  - id: lnu
    entityIDs:
      - https://idp.lnu.se/idp/shibboleth
      - https://idp.qa.lnu.se/idp/shibboleth
  - id: ltu
    entityIDs:
      - https://idp.ltu.se/idp/shibboleth
  - id: lu
    entityIDs:
      - https://idpv4.lu.se/idp/shibboleth
  - id: mau
    entityIDs:
      - http://sts.mau.se/adfs/services/trust
  - id: esh
    entityIDs:
      - https://idp.esh.se/idp/shibboleth
  - id: miun
    entityIDs:
      - https://miunidp.miun.se/idp/shibboleth
  - id: kb
    entityIDs:
      - http://sso.kb.se/adfs/services/trust
  - id: slu
    entityIDs:
      - http://idp-fs.slu.se/adfs/services/trust
      - https://idp-shib.slu.se/idp
  - id: kmh
    entityIDs:
      - https://idp.kmh.se/idp/shibboleth
  - id: kkh
    entityIDs:
      - https://idp2.kkh.se/idp/shibboleth
      - https://idp.kkh.se/idp/shibboleth
  - id: smhi
    entityIDs:
      - https://weblogin.smhi.se/idp/shibboleth
  - id: sunet
    entityIDs:
      - https://connect.eduid.se/sunet
      - https://idp.sunet.se/idp
  - id: shh
    entityIDs:
      - https://swamid2.shh.se/idp/shibboleth
  - id: su
    entityIDs:
      - https://idp.it.su.se/idp/shibboleth
  - id: uniarts
    entityIDs:
      - http://webproxysrv.uniarts.se/adfs/services/trust
      - https://idp.uniarts.se/idp/shibboleth
  - id: fhs
    entityIDs:
      - http://login2.fhs.se/adfs/services/trust
  - id: irf
    entityIDs:
      - https://idpshibboleth.irf.se/idp/shibboleth
  - id: nrm
    entityIDs:
      - http://fs.nrm.se/adfs/services/trust
  - id: rkh
    entityIDs:
      - http://adfs.rkh.se/adfs/services/trust
  - id: suni
    entityIDs:
      - https://idp-v2.suni.se/adfs/services/trust
  - id: kva
    entityIDs:
      - https://idp.kva.se/idp/shibboleth
  - id: uhr
    entityIDs:
      - https://shibboleth.uhr.se/idp/shibboleth
  - id: vr
    entityIDs:
      - http://idp.vr.se/adfs/services/trust
  - id: gih
    entityIDs:
      - https://idp01.gih.se/idp/shibboleth
  - id: umu
    entityIDs:
      - http://adfs.umu.se/adfs/services/trust
  - id: ths
    entityIDs:
      - https://idp.ths.se/idp/shibboleth
  - id: hv
    entityIDs:
      - http://adfs.hv.se/adfs/services/trust
  - id: hb
    entityIDs:
      - https://idp.hb.se/idp/shibboleth
  - id: gu
    entityIDs:
      - https://idp3.it.gu.se/idp/shibboleth
  - id: hig
    entityIDs:
      - https://idp3.hig.se/idp/shibboleth
  - id: his
    entityIDs:
      - https://idp.his.se/idp/shibboleth
  - id: antagning
    entityIDs:
      - https://idp.test.antagning.se/aws-idp
      - https://idp.antagning.se/aws-idp
  - id: oru
    entityIDs:
      - https://idp.oru.se/idp/shibboleth
      - https://shib-idp-1.oru.se/idp/shibboleth
