---
domain: drive.test.sunet.se
sites:
  - antagning
  - bth
  - chalmers
  - du
  - esh
  - extern
  - fhs
  - gih
  - gu
  - hb
  - hh
  - hhs
  - hig
  - his
  - hj
  - hkr
  - hv
  - irf
  - kau
  - kb
  - ki
  - kkh
  - kmh
  - konstfack
  - kth
  - kva
  - liu
  - lnu
  - ltu
  - lu
  - mau
  - mdu
  - miun
  - nordunet
  - nrm
  - oru
  - rkh
  - scilifelab
  - shh
  - sics
  - slu
  - smhi
  - sp
  - su
  - sunet
  - suni
  - swamid
  - ths
  - uhr
  - umu
  - uniarts
  - uu
  - vinnova
  - vr
